from trenpixster/elixir

run git init && git remote add origin https://github.com/hun7err/misra-token.git
run git fetch
run git checkout -t origin/master
run mix deps.get
run mix compile && mix escript.build

expose 4369
